clear; clc;
%Iterate in the directory which contains the `.dat` binary file generated by
%csitool. Convert each dat format file to mat format file.

amp_or_angle = 0; % 0 for amplitude, 1 for angle, 2 for complex.

dir_name = '/media/dataset/CSI/human-identification/';
subdirs = dir(dir_name);

for dir_idx = 1:length(subdirs);
    subdir = subdirs(dir_idx).name;
    if (~ isempty(regexp(subdir, '20220416')))
        printf("Current subdir: %s\n\n\", subdir);
        file_list = dir(strcat(dir_name, subdir));
        for i = 1:length(file_list);
            file_name = file_list(i).name;
            start_index = regexp(file_name, '\.dat$');
            if (~ isempty(start_index))
                abs_dat_name = strcat(dir_name, subdir, '/', file_name);
                printf("Current filename: %s\n", file_name);
                printf("Generated new filename: %s\n", abs_dat_name);
                dat2mat(abs_dat_name, amp_or_angle);
            end
        end
    end
    
end

